// (Item 6, p.43)

// Don't use auto for references to bools within vectors
#include <vector>

std::vector<bool> feature();

auto priority = feature()[5]; // priority is type std::vector<bool>::reference

// Instead, declare priority's type explicitly
bool priority = feature()[5];

// Or a better approach is to employ explicitly typed initialiser idiom.
// The latter makes it obvious we are deliberately creating a variable
// of a type different from that generated by the initialising expression
auto priority = static_cast<bool>(feature()[5]);
